imagePullPolicy: IfNotPresent

gateway:
  image: nginxinc/nginx-unprivileged:1.27-alpine
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

authService:
  image: securecloud/auth-service:latest
  replicas: 1
  port: 4000
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 256Mi

resourceService:
  image: securecloud/resource-service:latest
  replicas: 1
  port: 8000
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 256Mi

postgres:
  image: postgres:16
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  image: redis:7-alpine
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi