events { worker_connections 1024; }

http {
    upstream auth_backend {
        server auth-service:4000;
    }

    upstream resource_backend {
        server resource-service:8000;
    }

    server {
        listen 80;

        # 1. Auth endpoints
        location /auth/ {
            proxy_pass http://auth_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Protected API endpoints routed to FastAPI
        location /api/ {
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://resource_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}