apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: secure-cloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<797776210271>:role/auth-service-irsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-own-configmaps
  namespace: secure-cloud
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-configmap-binding
  namespace: secure-cloud
subjects:
  - kind: ServiceAccount
    name: auth-service-sa
roleRef:
  kind: Role
  name: read-own-configmaps
  apiGroup: rbac.authorization.k8s.io
