scrape_configs:
  - job_name: "auth-service"
    kubernetes_sd_configs:
      - role: pod
        namespaces: { names: [secure-cloud] }
    relabel_configs:
      - source_labels: [_meta_kubernetes_pod_label_app]
        regex: auth-service
        action: keep
    metrics_path: /metrics

  - job_name: "resource-service"
    kubernetes_sd_configs:
      - role: pod
        namespaces: { names: [secure-cloud] }
    relabel_configs:
      - source_labels: [_meta_kubernetes_pod_label_app]
        regex: resource-service
        action: keep
    metrics_path: /metrics
