name: Container Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, resource-service]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Scan Application Directory with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: services/${{ matrix.service }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL
          scanners: vuln
          hide-progress: true
          skip-dirs: "**/node_modules"